In [ ]:
{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "name": "script.ipynb",
      "provenance": [],
      "collapsed_sections": []
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "code",
      "execution_count": 3,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 424
        },
        "id": "p7jqTdGZ1jd-",
        "outputId": "63d706cc-8960-4ba9-9d44-529a2cb127a9"
      },
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "               Day       Entity Code  debt_relief  vaccination_policy  \\\n",
              "0       2020-01-01  Afghanistan  AFG          0.0                 0.0   \n",
              "1       2020-01-01      Albania  ALB          0.0                 0.0   \n",
              "2       2020-01-01      Algeria  DZA          0.0                 0.0   \n",
              "3       2020-01-01      Andorra  AND          0.0                 0.0   \n",
              "4       2020-01-01       Angola  AGO          0.0                 0.0   \n",
              "...            ...          ...  ...          ...                 ...   \n",
              "161750  2022-05-14    Venezuela  VEN          NaN                 NaN   \n",
              "161751  2022-05-14      Vietnam  VNM          NaN                 NaN   \n",
              "161752  2022-05-14        Yemen  YEM          NaN                 NaN   \n",
              "161753  2022-05-14       Zambia  ZMB          NaN                 NaN   \n",
              "161754  2022-05-14     Zimbabwe  ZWE          NaN                 NaN   \n",
              "\n",
              "        facial_coverings  cancel_public_events  \n",
              "0                    0.0                   0.0  \n",
              "1                    0.0                   0.0  \n",
              "2                    0.0                   0.0  \n",
              "3                    0.0                   0.0  \n",
              "4                    0.0                   0.0  \n",
              "...                  ...                   ...  \n",
              "161750               NaN                   NaN  \n",
              "161751               NaN                   NaN  \n",
              "161752               NaN                   NaN  \n",
              "161753               NaN                   NaN  \n",
              "161754               NaN                   NaN  \n",
              "\n",
              "[161755 rows x 7 columns]"
            ],
            "text/html": [
              "\n",
              "  <div id=\"df-addea40d-72a8-4359-be2f-177b4b074272\">\n",
              "    <div class=\"colab-df-container\">\n",
              "      <div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>Day</th>\n",
              "      <th>Entity</th>\n",
              "      <th>Code</th>\n",
              "      <th>debt_relief</th>\n",
              "      <th>vaccination_policy</th>\n",
              "      <th>facial_coverings</th>\n",
              "      <th>cancel_public_events</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>0</th>\n",
              "      <td>2020-01-01</td>\n",
              "      <td>Afghanistan</td>\n",
              "      <td>AFG</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>1</th>\n",
              "      <td>2020-01-01</td>\n",
              "      <td>Albania</td>\n",
              "      <td>ALB</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>2</th>\n",
              "      <td>2020-01-01</td>\n",
              "      <td>Algeria</td>\n",
              "      <td>DZA</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>3</th>\n",
              "      <td>2020-01-01</td>\n",
              "      <td>Andorra</td>\n",
              "      <td>AND</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>4</th>\n",
              "      <td>2020-01-01</td>\n",
              "      <td>Angola</td>\n",
              "      <td>AGO</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>...</th>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>161750</th>\n",
              "      <td>2022-05-14</td>\n",
              "      <td>Venezuela</td>\n",
              "      <td>VEN</td>\n",
              "      <td>NaN</td>\n",
              "      <td>NaN</td>\n",
              "      <td>NaN</td>\n",
              "      <td>NaN</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>161751</th>\n",
              "      <td>2022-05-14</td>\n",
              "      <td>Vietnam</td>\n",
              "      <td>VNM</td>\n",
              "      <td>NaN</td>\n",
              "      <td>NaN</td>\n",
              "      <td>NaN</td>\n",
              "      <td>NaN</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>161752</th>\n",
              "      <td>2022-05-14</td>\n",
              "      <td>Yemen</td>\n",
              "      <td>YEM</td>\n",
              "      <td>NaN</td>\n",
              "      <td>NaN</td>\n",
              "      <td>NaN</td>\n",
              "      <td>NaN</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>161753</th>\n",
              "      <td>2022-05-14</td>\n",
              "      <td>Zambia</td>\n",
              "      <td>ZMB</td>\n",
              "      <td>NaN</td>\n",
              "      <td>NaN</td>\n",
              "      <td>NaN</td>\n",
              "      <td>NaN</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>161754</th>\n",
              "      <td>2022-05-14</td>\n",
              "      <td>Zimbabwe</td>\n",
              "      <td>ZWE</td>\n",
              "      <td>NaN</td>\n",
              "      <td>NaN</td>\n",
              "      <td>NaN</td>\n",
              "      <td>NaN</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "<p>161755 rows × 7 columns</p>\n",
              "</div>\n",
              "      <button class=\"colab-df-convert\" onclick=\"convertToInteractive('df-addea40d-72a8-4359-be2f-177b4b074272')\"\n",
              "              title=\"Convert this dataframe to an interactive table.\"\n",
              "              style=\"display:none;\">\n",
              "        \n",
              "  <svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24px\"viewBox=\"0 0 24 24\"\n",
              "       width=\"24px\">\n",
              "    <path d=\"M0 0h24v24H0V0z\" fill=\"none\"/>\n",
              "    <path d=\"M18.56 5.44l.94 2.06.94-2.06 2.06-.94-2.06-.94-.94-2.06-.94 2.06-2.06.94zm-11 1L8.5 8.5l.94-2.06 2.06-.94-2.06-.94L8.5 2.5l-.94 2.06-2.06.94zm10 10l.94 2.06.94-2.06 2.06-.94-2.06-.94-.94-2.06-.94 2.06-2.06.94z\"/><path d=\"M17.41 7.96l-1.37-1.37c-.4-.4-.92-.59-1.43-.59-.52 0-1.04.2-1.43.59L10.3 9.45l-7.72 7.72c-.78.78-.78 2.05 0 2.83L4 21.41c.39.39.9.59 1.41.59.51 0 1.02-.2 1.41-.59l7.78-7.78 2.81-2.81c.8-.78.8-2.07 0-2.86zM5.41 20L4 18.59l7.72-7.72 1.47 1.35L5.41 20z\"/>\n",
              "  </svg>\n",
              "      </button>\n",
              "      \n",
              "  <style>\n",
              "    .colab-df-container {\n",
              "      display:flex;\n",
              "      flex-wrap:wrap;\n",
              "      gap: 12px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert {\n",
              "      background-color: #E8F0FE;\n",
              "      border: none;\n",
              "      border-radius: 50%;\n",
              "      cursor: pointer;\n",
              "      display: none;\n",
              "      fill: #1967D2;\n",
              "      height: 32px;\n",
              "      padding: 0 0 0 0;\n",
              "      width: 32px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert:hover {\n",
              "      background-color: #E2EBFA;\n",
              "      box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);\n",
              "      fill: #174EA6;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert {\n",
              "      background-color: #3B4455;\n",
              "      fill: #D2E3FC;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert:hover {\n",
              "      background-color: #434B5C;\n",
              "      box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);\n",
              "      filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));\n",
              "      fill: #FFFFFF;\n",
              "    }\n",
              "  </style>\n",
              "\n",
              "      <script>\n",
              "        const buttonEl =\n",
              "          document.querySelector('#df-addea40d-72a8-4359-be2f-177b4b074272 button.colab-df-convert');\n",
              "        buttonEl.style.display =\n",
              "          google.colab.kernel.accessAllowed ? 'block' : 'none';\n",
              "\n",
              "        async function convertToInteractive(key) {\n",
              "          const element = document.querySelector('#df-addea40d-72a8-4359-be2f-177b4b074272');\n",
              "          const dataTable =\n",
              "            await google.colab.kernel.invokeFunction('convertToInteractive',\n",
              "                                                     [key], {});\n",
              "          if (!dataTable) return;\n",
              "\n",
              "          const docLinkHtml = 'Like what you see? Visit the ' +\n",
              "            '<a target=\"_blank\" href=https://colab.research.google.com/notebooks/data_table.ipynb>data table notebook</a>'\n",
              "            + ' to learn more about interactive tables.';\n",
              "          element.innerHTML = '';\n",
              "          dataTable['output_type'] = 'display_data';\n",
              "          await google.colab.output.renderOutput(dataTable, element);\n",
              "          const docLink = document.createElement('div');\n",
              "          docLink.innerHTML = docLinkHtml;\n",
              "          element.appendChild(docLink);\n",
              "        }\n",
              "      </script>\n",
              "    </div>\n",
              "  </div>\n",
              "  "
            ]
          },
          "metadata": {},
          "execution_count": 3
        }
      ],
      "source": [
        "import pandas as pd\n",
        "df1 = pd.read_csv(\"/content/debt-relief-covid.csv\")\n",
        "df2 = pd.read_csv(\"/content/covid-vaccination-policy.csv\")\n",
        "df3 = pd.read_csv(\"/content/face-covering-policies-covid.csv\")\n",
        "df4 = pd.read_csv(\"/content/public-events-covid.csv\")\n",
        "df1_ent = df1[['Entity','Code']].drop_duplicates()\n",
        "df2_ent = df2[['Entity','Code']].drop_duplicates()\n",
        "df3_ent = df3[['Entity','Code']].drop_duplicates()\n",
        "df4_ent = df4[['Entity','Code']].drop_duplicates()\n",
        "countries = pd.concat([df1_ent,df2_ent,df3_ent,df4_ent], ignore_index=True).drop_duplicates().sort_values(by=['Entity'])\n",
        "df1_days = df1['Day'].drop_duplicates()\n",
        "df2_days = df2['Day'].drop_duplicates()\n",
        "df3_days = df3['Day'].drop_duplicates()\n",
        "df4_days = df4['Day'].drop_duplicates()\n",
        "days = pd.DataFrame(pd.concat([df1_days,df2_days,df3_days,df4_days], ignore_index=True).drop_duplicates()).sort_values(by=['Day'])\n",
        "intermediate_df = days.merge(countries, how='cross')\n",
        "final_debt_relief = pd.merge(intermediate_df,df1,on=['Entity','Code','Day'],how='left')\n",
        "final_vaccination = pd.merge(final_debt_relief,df2,on=['Entity','Code','Day'],how='left')\n",
        "final_face_covering_policies = pd.merge(final_vaccination,df3,on=['Entity','Code','Day'],how='left')\n",
        "final_df = pd.merge(final_face_covering_policies,df4,on=['Entity','Code','Day'],how='left')\n",
        "final_df"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "final_df.to_excel(\"data.xlsx\")"
      ],
      "metadata": {
        "id": "p55-jG5s8kjs"
      },
      "execution_count": 10,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "final_df.to_csv('data.csv')"
      ],
      "metadata": {
        "id": "3x6QUIim9Ns1"
      },
      "execution_count": 11,
      "outputs": []
    }
  ]
}